//go:build !ignore_autogenerated

/*
Copyright 2023.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/util/intstr"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AnonymousHttpSource) DeepCopyInto(out *AnonymousHttpSource) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AnonymousHttpSource.
func (in *AnonymousHttpSource) DeepCopy() *AnonymousHttpSource {
	if in == nil {
		return nil
	}
	out := new(AnonymousHttpSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeReference) DeepCopyInto(out *NodeReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeReference.
func (in *NodeReference) DeepCopy() *NodeReference {
	if in == nil {
		return nil
	}
	out := new(NodeReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RollingRolloutStrategy) DeepCopyInto(out *RollingRolloutStrategy) {
	*out = *in
	if in.MaxUnavailable != nil {
		in, out := &in.MaxUnavailable, &out.MaxUnavailable
		*out = new(intstr.IntOrString)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RollingRolloutStrategy.
func (in *RollingRolloutStrategy) DeepCopy() *RollingRolloutStrategy {
	if in == nil {
		return nil
	}
	out := new(RollingRolloutStrategy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Shim) DeepCopyInto(out *Shim) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Shim.
func (in *Shim) DeepCopy() *Shim {
	if in == nil {
		return nil
	}
	out := new(Shim)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Shim) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ShimList) DeepCopyInto(out *ShimList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Shim, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ShimList.
func (in *ShimList) DeepCopy() *ShimList {
	if in == nil {
		return nil
	}
	out := new(ShimList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ShimList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ShimRolloutStrategy) DeepCopyInto(out *ShimRolloutStrategy) {
	*out = *in
	if in.RollingRolloutStrategy != nil {
		in, out := &in.RollingRolloutStrategy, &out.RollingRolloutStrategy
		*out = new(RollingRolloutStrategy)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ShimRolloutStrategy.
func (in *ShimRolloutStrategy) DeepCopy() *ShimRolloutStrategy {
	if in == nil {
		return nil
	}
	out := new(ShimRolloutStrategy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ShimSource) DeepCopyInto(out *ShimSource) {
	*out = *in
	if in.AnonymousHttp != nil {
		in, out := &in.AnonymousHttp, &out.AnonymousHttp
		*out = new(AnonymousHttpSource)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ShimSource.
func (in *ShimSource) DeepCopy() *ShimSource {
	if in == nil {
		return nil
	}
	out := new(ShimSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ShimSpec) DeepCopyInto(out *ShimSpec) {
	*out = *in
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	in.Source.DeepCopyInto(&out.Source)
	in.RolloutStrategy.DeepCopyInto(&out.RolloutStrategy)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ShimSpec.
func (in *ShimSpec) DeepCopy() *ShimSpec {
	if in == nil {
		return nil
	}
	out := new(ShimSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ShimStatus) DeepCopyInto(out *ShimStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.UpgradedNodes != nil {
		in, out := &in.UpgradedNodes, &out.UpgradedNodes
		*out = make([]NodeReference, len(*in))
		copy(*out, *in)
	}
	if in.UpgradingNodes != nil {
		in, out := &in.UpgradingNodes, &out.UpgradingNodes
		*out = make([]NodeReference, len(*in))
		copy(*out, *in)
	}
	if in.QueuedNodes != nil {
		in, out := &in.QueuedNodes, &out.QueuedNodes
		*out = make([]NodeReference, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ShimStatus.
func (in *ShimStatus) DeepCopy() *ShimStatus {
	if in == nil {
		return nil
	}
	out := new(ShimStatus)
	in.DeepCopyInto(out)
	return out
}
